[build]
	publish = 'dist/'
	command = 'npm run build'
	functions = 'functions/'

[[redirects]]
	from = "/ffnet/"
	to = "/"
	status = 301

[[redirects]]
	from = "/hpffa/"
	to = "/"
	status = 301

[[redirects]]
	from = "/ao3/"
	to = "/"
	status = 301

[[redirects]]
	from = "/ffnet/:story"
	to = "/ffnet/:story/1"
	status = 301

[[redirects]]
	from = "/ffnet/:story/:chapter"
	to = "/.netlify/functions/ffnet/ffnet"
	status = 200

[[redirects]]
	from = "/hpffa/:story"
	to = "/hpffa/:story/1"
	status = 301

[[redirects]]
	from = "/hpffa/:story/:chapter"
	to = "/.netlify/functions/hpffa/hpffa"
	status = 200

[[redirects]]
	from = "/ao3/:story"
	to = "/.netlify/functions/ao3/ao3"
	status = 200

[[redirects]]
	from = "/ao3/:story/:chapter"
	to = "/.netlify/functions/ao3/ao3"
	status = 200

[[redirects]]
	from = "/favicon.ico"
	to = "/"
	status = 404
	force = false

[[redirects]]
	from = "/*"
	to = "/.netlify/functions/default/default"
	status = 200
	force = false
